/* ==========================================================================
   js/battle-3d.js - Battle Map "Command view" (3D), Phase 6a, 2026-10-03
   ==========================================================================
   DM decisions (2026-10-03):
   - The 2D grid stays as the flat "Classic" view, with every tool intact.
     This 3D view is a second view of the same battle, not a replacement.
   - Default per device: Command (3D) on desktop, Classic on phones. Anyone
     can switch; the choice is remembered per device (localStorage).
   - Altitude is VISUAL ONLY: auto by class (strike craft low, ships
     staggered, stations level) plus a per-token nudge stored in
     battle_tokens.z. It never touches range, movement or arcs.
   - Until GLB models exist, ships are low-poly hulls generated by class.

   How it fits:
   - Loads Three.js (pinned r170) from jsDelivr ONLY when someone opens
     this view. No WebGL, or the download fails -> Classic, automatically.
   - Hooks renderBattleMapPanel (after the tactical HUD's hook). The DOM
     grid keeps rendering underneath (hidden), so switching back is instant
     and every DOM-based tool keeps its state.
   - Moving uses the SAME rules as the 2D drag (battleMoveRule /
     battleConstrainMove / battleCommitMove in js/battle-map.js), placing
     uses placeArmedTokenAt, a tap uses battleTokenTapped.
   - Renders on demand only: 0 FPS while nothing changes or moves.
   - Behind the 'battle_3d' feature switch.
   Phase 6b (2026-10-03, DM defaults): ships glide to new positions/headings
   with a fading engine trail (moves only -- no constant animation); weapon
   effects per damage family; shields-up hits flash a blue bubble, shields-
   down hits throw hull sparks; bigger explosions; measuring tape in 3D
   (shared tapes both ways with the 2D view); quality HIGH/LOW (auto by
   device, ⚙ toggle remembered per device); on a phone in 3D the HUD bottom
   sheet starts as a slim bar (tap the name to open).

   Coordinates: grid (gx, gy) -> 3D (gx - W/2, altitude, gy - H/2). Y is up.
   Facing 0 (top of grid) = -Z; a hull's rotation.y = -facing.
   Loaded after js/tactical-hud.js. */
(function () {
const THREE_URL = 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.min.js';
const VIEW_KEY = 'darkforest_battle_view';
const B3 = {
    THREE: null, loading: null, failed: false,
    importer: null,        // test hook: (url) => Promise<module>
    createRenderer: null,  // test hook: (THREE, canvasHost) => renderer
    forceWebGL: null,      // test hook: true/false
    el: null, renderer: null, scene: null, camera: null,
    groups: {}, objs: {}, geo: {}, mats: {},
    cam: { tx: 0, tz: 0, yaw: 0, pitch: 55, dist: 1000 },
    pending: false, drag: null, pointers: {}, fx: [], lastEncId: null,
    selectedLocal: null, frames: 0, hintShown: false,
    tool: null, tape: null, sheetMini: true
};
window.__b3d = B3;

/* --- Availability / view choice --- */
function featureOn() { return typeof window.isFeatureOn === 'function' && window.isFeatureOn('battle_3d'); }
let webglOk = null;
function hasWebGL() {
    if (B3.forceWebGL !== null) return !!B3.forceWebGL;
    if (webglOk !== null) return webglOk;
    try {
        const c = document.createElement('canvas');
        webglOk = !!(window.WebGLRenderingContext && (c.getContext('webgl2') || c.getContext('webgl')));
    } catch (e) { webglOk = false; }
    return webglOk;
}
function isPhone() {
    try { return window.matchMedia('(max-width: 768px)').matches || window.matchMedia('(pointer: coarse)').matches; } catch (e) { return false; }
}
window.battle3dPreferredView = function () {
    let v = null;
    try { v = localStorage.getItem(VIEW_KEY); } catch (e) {}
    if (v === 'command' || v === 'classic') return v;
    return isPhone() ? 'classic' : 'command';
};
window.battle3dAvailable = function () { return featureOn() && hasWebGL() && !B3.failed; };
window.battle3dActive = function () {
    return window.battle3dAvailable() && !!window.globalBattleEncounterCache && window.battle3dPreferredView() === 'command';
};
window.setBattleView = function (v) {
    try { localStorage.setItem(VIEW_KEY, v === 'command' ? 'command' : 'classic'); } catch (e) {}
    if (typeof window.renderBattleMapPanel === 'function') window.renderBattleMapPanel();
};
window.toggleBattleView = function () {
    window.setBattleView(window.battle3dActive() ? 'classic' : 'command');
};

/* --- Quality (Phase 6b) --- */
const QUALITY_KEY = 'darkforest_battle_quality';
window.battle3dQuality = function () {
    let q = null;
    try { q = localStorage.getItem(QUALITY_KEY); } catch (e) {}
    if (q === 'high' || q === 'low') return q;
    return isPhone() ? 'low' : 'high';
};
function lowQ() { return window.battle3dQuality() === 'low'; }
function applyQuality() {
    if (!B3.renderer) return;
    B3.renderer.setPixelRatio(lowQ() ? 1 : Math.min(window.devicePixelRatio || 1, 2));
    B3._w = null; resize();
    requestRender();
}
window.setBattle3dQuality = function (q) {
    try { localStorage.setItem(QUALITY_KEY, q === 'low' ? 'low' : 'high'); } catch (e) {}
    applyQuality(); updateToolbar();
};

/* --- Small helpers --- */
const esc = (s) => window.escapeHtml ? window.escapeHtml(s == null ? '' : String(s)) : String(s == null ? '' : s);
function encTokens() { return (window.globalBattleEncounterCache && window.globalBattleEncounterCache.tokens) || []; }
function vesselById(id) { return globalShipMarkersCache.find(m => m.id === id) || null; }
function visibleToMe(v) { return !v || typeof window.isVesselVisibleToMe !== 'function' || window.isVesselVisibleToMe(v); }
function tokSize(v) { return (v && v.is_strike_craft) ? BATTLE_STRIKE_CRAFT_TOKEN_SIZE : BATTLE_TOKEN_SIZE; }
function tokCenter(tok) {
    if (typeof window.battleTokenCenter === 'function') return window.battleTokenCenter(tok);
    const s = tokSize(vesselById(tok.ship_marker_id));
    return { x: tok.x + s / 2, y: tok.y + s / 2 };
}
function hash(str) { let h = 0; str = String(str || ''); for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) | 0; return Math.abs(h); }
function factionColor(v) {
    try { if (typeof battleTokenFactionColor === 'function') return battleTokenFactionColor(v); } catch (e) {}
    return '#00e1ff';
}
function canControl(v) { return !!v && (currentUserRole === 'dm' || window.vesselHasOwner(v, currentUserId)); }
function selectedVesselId() {
    if (typeof window.tv2Active === 'function' && window.tv2Active() && window.__tv2) return window.__tv2.selected;
    return B3.selectedLocal;
}
function shipKind(v) {
    if (!v) return 'capital';
    if (v.is_station) return 'station';
    if (v.is_strike_craft) return 'craft';
    return /escort|frigate|corvette|destroyer/i.test(String(v.vessel_class || '')) ? 'escort' : 'capital';
}

/* --- Altitude (visual only) --- */
window.battle3dAutoAltitude = function (v, tok) {
    if (!v) return 30;
    if (v.is_station) return 8;
    if (v.is_strike_craft) return 16;
    const base = shipKind(v) === 'escort' ? 26 : 38;
    return base + (hash(tok && tok.token_id) % 3) * 12; // stagger so stacked ships don't merge
};
window.battle3dAltitude = function (v, tok) {
    return Math.max(2, window.battle3dAutoAltitude(v, tok) + (Number(tok && tok.z) || 0));
};
const HULL_SCALE = 1.7; // hulls read too small at the default zoom at 1:1
const ALT_STEP = 15, ALT_MIN = -40, ALT_MAX = 120;
window.nudgeBattleAltitude = async function (tokenId, delta) {
    const enc = window.globalBattleEncounterCache;
    if (!enc) return false;
    const tok = (enc.tokens || []).find(t => t.token_id === tokenId);
    const v = tok && vesselById(tok.ship_marker_id);
    if (!tok || !canControl(v) || v.is_station) return false;
    const z = Math.max(ALT_MIN, Math.min(ALT_MAX, (Number(tok.z) || 0) + delta));
    if (z === (Number(tok.z) || 0)) return true;
    const tokens = (enc.tokens || []).map(t => t.token_id === tokenId ? { ...t, z } : t);
    const save = () => saveBattleTokens(tokens);
    if (typeof window.recordBattleAction === 'function') await window.recordBattleAction('Altitude', save);
    else await save();
    if (typeof window.renderBattleMapPanel === 'function') window.renderBattleMapPanel();
    return true;
};

/* --- Grid <-> 3D --- */
function V(gx, gy, alt) { return new B3.THREE.Vector3(gx - BATTLE_GRID_W / 2, alt || 0, gy - BATTLE_GRID_H / 2); }
function toGrid(p) { return { x: p.x + BATTLE_GRID_W / 2, y: p.z + BATTLE_GRID_H / 2 }; }

/* --- Three.js loading --- */
function loadThree() {
    if (B3.THREE) return Promise.resolve(B3.THREE);
    if (!B3.loading) {
        const imp = B3.importer || ((u) => import(u));
        B3.loading = imp(THREE_URL).then(m => { B3.THREE = m; return m; }).catch(err => {
            console.error('3D view: could not load Three.js -- falling back to the 2D grid', err);
            B3.failed = true; B3.loading = null;
            throw err;
        });
    }
    return B3.loading;
}

/* --- DOM shell --- */
function ensureEls() {
    const stage = document.getElementById('battle-map-stage');
    if (!stage) return null;
    let el = document.getElementById('battle-3d-view');
    if (!el) {
        el = document.createElement('div');
        el.id = 'battle-3d-view';
        el.className = 'b3d-view';
        el.innerHTML = `<div class="b3d-canvas-host"></div>
            <div class="b3d-labels"></div>
            <div class="b3d-status">Loading 3D view…</div>
            <div class="b3d-toolbar">
                <button type="button" class="layer-edit" data-act="reset" title="Reset the camera">⟲ VIEW</button>
                <button type="button" class="layer-edit" data-act="top" title="Look straight down">⊤ TOP</button>
                <button type="button" class="layer-edit" data-act="tape" title="Measuring tape: drag on the plane (starts at a ship's centre if you start on one). Tap to clear. Right-drag still pans.">📏 TAPE</button>
                <button type="button" class="layer-edit" data-act="share" title="Show my tape on everyone's map">📡 SHARE</button>
                <button type="button" class="layer-edit" data-act="quality" title="Graphics quality (remembered on this device)">⚙ HIGH</button>
                <span class="b3d-sel-tools">
                    <button type="button" class="layer-edit" data-act="turnL" title="Turn the selected ship 15° left">⟲ 15°</button>
                    <button type="button" class="layer-edit" data-act="turnR" title="Turn the selected ship 15° right">⟳ 15°</button>
                    <button type="button" class="layer-edit" data-act="altU" title="Raise the selected ship (looks only -- no effect on range or movement)">ALT ▲</button>
                    <button type="button" class="layer-edit" data-act="altD" title="Lower the selected ship (looks only)">ALT ▼</button>
                </span>
            </div>
            <div class="b3d-hint">Drag empty space to orbit · right-drag or Shift-drag to pan · wheel / pinch to zoom · drag your ship to move it · tap a ship to select it</div>`;
        const wrap = document.getElementById('battle-map-grid-wrap');
        stage.insertBefore(el, wrap ? wrap.nextSibling : null);
        el.querySelector('.b3d-toolbar').addEventListener('click', onToolbar);
        wireInput(el);
    }
    B3.el = el;
    return el;
}
function ensureHeaderButton() {
    let btn = document.getElementById('battle-map-view-btn');
    if (!btn) {
        const anchor = document.getElementById('battle-map-log-btn') || document.getElementById('battle-map-end-btn');
        if (!anchor || !anchor.parentNode) return;
        btn = document.createElement('button');
        btn.id = 'battle-map-view-btn';
        btn.type = 'button';
        btn.className = 'layer-edit';
        btn.style.cssText = 'font-size:9px; padding:3px 8px;';
        btn.onclick = () => window.toggleBattleView();
        anchor.parentNode.insertBefore(btn, anchor);
    }
    const avail = window.battle3dAvailable() && !!window.globalBattleEncounterCache;
    btn.style.display = avail ? 'inline-block' : 'none';
    const on = window.battle3dActive();
    btn.textContent = on ? '▦ 2D VIEW' : '🛰 3D VIEW';
    btn.title = on ? 'Switch to the flat grid (all grid tools)' : 'Switch to the 3D Command view';
}

/* --- Scene --- */
function initScene() {
    const T = B3.THREE;
    const host = B3.el.querySelector('.b3d-canvas-host');
    const renderer = B3.createRenderer ? B3.createRenderer(T, host)
        : new T.WebGLRenderer({ antialias: window.battle3dQuality() === 'high', powerPreference: 'low-power' });
    renderer.setPixelRatio(window.battle3dQuality() === 'low' ? 1 : Math.min(window.devicePixelRatio || 1, 2));
    if (renderer.domElement && !renderer.domElement.parentNode) host.appendChild(renderer.domElement);
    const scene = new T.Scene();
    scene.background = new T.Color(0x03070b);
    scene.fog = new T.Fog(0x03070b, 1500, 3200);
    const camera = new T.PerspectiveCamera(45, 1, 5, 6000);
    scene.add(new T.HemisphereLight(0xa8e6ff, 0x081018, 1.0));
    const sun = new T.DirectionalLight(0xffffff, 1.4);
    sun.position.set(300, 700, 250);
    scene.add(sun);

    // The tactical plane + grid
    const W = BATTLE_GRID_W, H = BATTLE_GRID_H;
    const plane = new T.Mesh(new T.PlaneGeometry(W, H), new T.MeshBasicMaterial({ color: 0x061318, transparent: true, opacity: 0.92 }));
    plane.rotation.x = -Math.PI / 2;
    scene.add(plane);
    const minor = [], major = [];
    for (let x = 0; x <= W; x += 40) (x % 200 === 0 ? major : minor).push(x - W / 2, 0.2, -H / 2, x - W / 2, 0.2, H / 2);
    for (let y = 0; y <= H; y += 40) (y % 200 === 0 ? major : minor).push(-W / 2, 0.2, y - H / 2, W / 2, 0.2, y - H / 2);
    const lines = (arr, color, opacity) => {
        const g = new T.BufferGeometry();
        g.setAttribute('position', new T.Float32BufferAttribute(arr, 3));
        return new T.LineSegments(g, new T.LineBasicMaterial({ color, transparent: true, opacity }));
    };
    scene.add(lines(minor, 0x1a4652, 0.45));
    scene.add(lines(major, 0x2a7f8f, 0.7));
    scene.add(lines([-W / 2, 0.3, -H / 2, W / 2, 0.3, -H / 2, W / 2, 0.3, -H / 2, W / 2, 0.3, H / 2, W / 2, 0.3, H / 2, -W / 2, 0.3, H / 2, -W / 2, 0.3, H / 2, -W / 2, 0.3, -H / 2], 0x3fc6d8, 0.9));

    ['tokens', 'overlay', 'fx', 'preview', 'tape'].forEach(k => { B3.groups[k] = new T.Group(); scene.add(B3.groups[k]); });
    Object.assign(B3, { renderer, scene, camera, plane });
    resetCamera();
    try { window.addEventListener('resize', () => { resize(); requestRender(); }); } catch (e) {}
}
function resize() {
    if (!B3.renderer || !B3.el) return;
    const w = Math.max(50, B3.el.clientWidth || 720), h = Math.max(50, B3.el.clientHeight || 600);
    if (B3._w === w && B3._h === h) return;
    B3._w = w; B3._h = h;
    B3.renderer.setSize(w, h, true);
    B3.camera.aspect = w / h;
    B3.camera.updateProjectionMatrix();
}
function fitDist(pitchDeg) {
    const aspect = (B3._w || 720) / (B3._h || 600);
    const vfov = 45 * Math.PI / 180;
    const needH = BATTLE_GRID_H * 0.55 + 40, needW = BATTLE_GRID_W * 0.55 + 40;
    const dH = needH / Math.tan(vfov / 2);
    const dW = needW / (Math.tan(vfov / 2) * aspect);
    const flat = pitchDeg > 80 ? 1 : 0.92;
    return Math.max(dH, dW) * flat;
}
function resetCamera() { resize(); Object.assign(B3.cam, { tx: 0, tz: 40, yaw: 0, pitch: 52 }); B3.cam.dist = fitDist(52); requestRender(); }
function topCamera() { resize(); Object.assign(B3.cam, { tx: 0, tz: 0, yaw: 0, pitch: 89.5 }); B3.cam.dist = fitDist(89.5); requestRender(); }
window.battle3dResetCamera = resetCamera;
window.battle3dTopCamera = topCamera;
function applyCamera() {
    const c = B3.cam, p = c.pitch * Math.PI / 180, y = c.yaw * Math.PI / 180;
    B3.camera.position.set(c.tx + c.dist * Math.cos(p) * Math.sin(y), c.dist * Math.sin(p), c.tz + c.dist * Math.cos(p) * Math.cos(y));
    B3.camera.lookAt(c.tx, 0, c.tz);
    B3.camera.updateMatrixWorld();
}

/* --- Shared geometry / materials --- */
function geo(key) {
    if (B3.geo[key]) return B3.geo[key];
    const T = B3.THREE;
    let g;
    if (key === 'capital') { g = new T.ConeGeometry(10, 36, 4); g.rotateX(-Math.PI / 2); g.scale(1, 0.42, 1); }
    else if (key === 'escort') { g = new T.ConeGeometry(7.5, 27, 4); g.rotateX(-Math.PI / 2); g.scale(1, 0.42, 1); }
    else if (key === 'bridge') { g = new T.BoxGeometry(5, 4, 9); }
    else if (key === 'craft') { g = new T.ConeGeometry(5, 14, 3); g.rotateX(-Math.PI / 2); g.scale(1, 0.35, 1); }
    else if (key === 'station') { g = new T.TorusGeometry(13, 2.6, 6, 18); g.rotateX(Math.PI / 2); }
    else if (key === 'stationCore') { g = new T.CylinderGeometry(4.5, 4.5, 11, 8); }
    else if (key === 'glow') { g = new T.SphereGeometry(2.2, 10, 8); }
    else if (key === 'unitLine') { g = new T.BufferGeometry().setFromPoints([new T.Vector3(0, 0, 0), new T.Vector3(0, 1, 0)]); }
    else if (key.startsWith('ring:')) { const [, a, b] = key.split(':').map(Number); g = new T.RingGeometry(a, b, 40); g.rotateX(-Math.PI / 2); }
    else if (key.startsWith('disc:')) { const r = Number(key.split(':')[1]); g = new T.CircleGeometry(r, 40); g.rotateX(-Math.PI / 2); }
    B3.geo[key] = g;
    return g;
}
function mat(kind, color, opacity) {
    const key = `${kind}|${color}|${opacity == null ? 1 : opacity}`;
    if (B3.mats[key]) return B3.mats[key];
    const T = B3.THREE;
    const transparent = opacity != null && opacity < 1;
    let m;
    if (kind === 'hull') m = new T.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: 0.22, metalness: 0.35, roughness: 0.55, flatShading: true, transparent, opacity: opacity == null ? 1 : opacity });
    else if (kind === 'line') m = new T.LineBasicMaterial({ color, transparent: true, opacity: opacity == null ? 1 : opacity });
    else if (kind === 'glow') m = new T.MeshBasicMaterial({ color, transparent: true, opacity: opacity == null ? 1 : opacity, blending: T.AdditiveBlending, depthWrite: false });
    else if (kind === 'dash') m = new T.LineDashedMaterial({ color, transparent: true, opacity: opacity == null ? 1 : opacity, dashSize: 8, gapSize: 6 });
    else m = new T.MeshBasicMaterial({ color, transparent: true, opacity: opacity == null ? 1 : opacity, side: T.DoubleSide, depthWrite: false });
    B3.mats[key] = m;
    return m;
}
function lineObj(points, color, opacity, dashed) {
    const T = B3.THREE;
    const g = new T.BufferGeometry().setFromPoints(points);
    const l = new T.Line(g, mat(dashed ? 'dash' : 'line', color, opacity));
    if (dashed) l.computeLineDistances();
    l.userData.ownGeo = true;
    return l;
}
function disposeTree(obj) {
    obj.traverse(o => { if (o.userData && o.userData.ownGeo && o.geometry) o.geometry.dispose(); });
}

/* --- Tokens --- */
function buildHull(kind, color, ghost) {
    const T = B3.THREE;
    const g = new T.Group();
    const m = mat('hull', color, ghost ? 0.45 : null);
    if (kind === 'station') {
        g.add(new T.Mesh(geo('station'), m));
        g.add(new T.Mesh(geo('stationCore'), m));
    } else {
        g.add(new T.Mesh(geo(kind), m));
        // Engine glow at the stern (Phase 6b); brightens while the ship moves.
        const glow = new T.Mesh(geo('glow'), mat('glow', '#9ff3ff', ghost ? 0.35 : 0.85));
        glow.position.set(0, 0, kind === 'craft' ? 7.5 : kind === 'escort' ? 13.5 : 18);
        glow.userData.isGlow = true;
        g.add(glow);
        g.userData.glow = glow;
        if (kind !== 'craft') {
            const br = new T.Mesh(geo('bridge'), m);
            br.position.set(0, 3.2, kind === 'escort' ? 4 : 6);
            g.add(br);
        }
    }
    return g;
}
function upsertToken(tok, v, enc, currentTurnId, selId) {
    const T = B3.THREE;
    const id = tok.token_id;
    const kind = shipKind(v);
    const color = factionColor(v);
    const ghost = !!(v && v.is_hidden && currentUserRole === 'dm');
    const sig = `${kind}|${color}|${ghost}`;
    let o = B3.objs[id];
    if (!o || o.sig !== sig) {
        if (o) { B3.groups.tokens.remove(o.group); disposeTree(o.group); }
        const group = new T.Group();
        const hull = buildHull(kind, color, ghost);
        hull.scale.setScalar(HULL_SCALE);
        const r = kind === 'craft' ? 11 : kind === 'station' ? 20 : 19;
        const disc = new T.Mesh(geo(`disc:${r}`), mat('flat', color, 0.13)); disc.position.y = 0.4;
        const rim = new T.Mesh(geo(`ring:${r - 1.6}:${r}`), mat('flat', color, 0.85)); rim.position.y = 0.5;
        const turn = new T.Mesh(geo(`ring:${r + 3}:${r + 5.5}`), mat('flat', '#ffd24a', 0.95)); turn.position.y = 0.6;
        const sel = new T.Mesh(geo(`ring:${r + 7}:${r + 8.5}`), mat('flat', '#ffffff', 0.9)); sel.position.y = 0.7;
        const nose = lineObj([new T.Vector3(0, 0.8, 0), new T.Vector3(0, 0.8, -(r + 10))], color, 0.8);
        const noseHolder = new T.Group(); noseHolder.add(nose);
        group.add(hull, disc, rim, turn, sel, noseHolder);
        [hull, disc, rim].forEach(obj => obj.traverse(c => { c.userData.tokenId = id; c.userData.vesselId = tok.ship_marker_id; }));
        const label = document.createElement('div');
        label.className = 'b3d-label';
        B3.el.querySelector('.b3d-labels').appendChild(label);
        const drop = new T.Line(geo('unitLine'), mat('line', color, 0.55));
        group.add(drop);
        o = { group, hull, disc, rim, turn, sel, noseHolder, drop, label, sig, cur: null, shown: null, anim: null };
        B3.objs[id] = o;
        B3.groups.tokens.add(group);
    }
    const c = tokCenter(tok);
    const dragging = B3.drag && B3.drag.kind === 'ship' && B3.drag.tokenId === id && B3.drag.moved;
    const target = { x: c.x - BATTLE_GRID_W / 2, z: c.y - BATTLE_GRID_H / 2, y: window.battle3dAltitude(v, tok), rot: -((Number(tok.facing) || 0) * Math.PI / 180) };
    if (!o.cur) { o.cur = target; o.shown = Object.assign({}, target); }
    else if (!dragging && stateDiffers(o.cur, target)) startTween(o, target, color);
    if (!dragging && !o.anim) applyShown(o, o.cur);
    o.noseHolder.visible = !!(v && !v.is_strike_craft && !v.is_station && window.firingArcsOn && window.firingArcsOn());
    o.turn.visible = !!(currentTurnId && currentTurnId === id);
    o.sel.visible = !!(selId && v && selId === v.id);
    o.vesselId = tok.ship_marker_id;
    // Label: name + hull/shield bars
    const name = v ? v.name : '???';
    const hullPct = v && v.max_hull > 0 ? Math.max(0, Math.min(100, (v.integrity_hull || 0) / v.max_hull * 100)) : 0;
    const shPct = v && v.max_shields > 0 ? Math.max(0, Math.min(100, (v.integrity_shields || 0) / v.max_shields * 100)) : 0;
    const hullCol = hullPct > 66 ? '#00e5a3' : hullPct > 33 ? '#ffaa00' : '#ff4d4d';
    const html = `<div class="b3d-name" style="color:${esc(color)}">${o.turn.visible ? '▶ ' : ''}${esc(name)}</div>`
        + (v && !v.is_strike_craft ? `<div class="b3d-bar"><i style="width:${hullPct.toFixed(0)}%; background:${hullCol}"></i></div>`
        + (v.max_shields > 0 ? `<div class="b3d-bar b3d-bar-sh"><i style="width:${shPct.toFixed(0)}%"></i></div>` : '') : '');
    if (o.labelHtml !== html) { o.label.innerHTML = html; o.labelHtml = html; }
    o.label.classList.toggle('b3d-label-sel', o.sel.visible);
    o.label.classList.toggle('b3d-label-craft', kind === 'craft');
}
/* --- Movement tweens + trails (Phase 6b) --- */
function angDiff(a, b) { let d = (b - a) % (Math.PI * 2); if (d > Math.PI) d -= Math.PI * 2; if (d < -Math.PI) d += Math.PI * 2; return d; }
function stateDiffers(a, b) { return Math.hypot(a.x - b.x, a.z - b.z) > 0.5 || Math.abs(a.y - b.y) > 0.1 || Math.abs(angDiff(a.rot, b.rot)) > 0.002; }
function applyShown(o, st) {
    o.shown = Object.assign({}, st);
    o.group.position.set(st.x, 0, st.z);
    o.hull.position.y = st.y;
    o.hull.rotation.y = st.rot;
    o.noseHolder.rotation.y = st.rot;
    o.drop.scale.y = Math.max(0.5, st.y);
}
function startTween(o, target, color) {
    const from = Object.assign({}, o.shown || o.cur);
    const dist = Math.hypot(target.x - from.x, target.z - from.z);
    o.cur = target;
    o.anim = { from, to: target, t0: nowMs(), dur: dist > 1 ? Math.min(900, 350 + dist * 2.5) : 320 };
    if (dist > 3) addTrail({ x: from.x, y: from.y, z: from.z }, { x: target.x, y: target.y, z: target.z }, color);
    requestRender();
}
window.battle3dCommitDragPosition = function (tokenId, gx, gy) { // a local drag already shows the ship at the drop point
    const o = B3.objs[tokenId];
    if (!o || !o.cur) return;
    const start = Object.assign({}, o.cur);
    o.cur = Object.assign({}, o.cur, { x: gx - BATTLE_GRID_W / 2, z: gy - BATTLE_GRID_H / 2 });
    o.anim = null;
    applyShown(o, o.cur);
    const col = o.sig.split('|')[1];
    if (Math.hypot(o.cur.x - start.x, o.cur.z - start.z) > 3) addTrail(start, o.cur, col);
};
function stepAnims(now) {
    let busy = false;
    Object.values(B3.objs).forEach(o => {
        const glow = o.hull.userData.glow;
        if (!o.anim) { if (glow) glow.scale.setScalar(1); return; }
        const k = Math.min(1, (now - o.anim.t0) / o.anim.dur);
        const e = k < 0.5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2; // ease in-out
        const f = o.anim.from, t = o.anim.to;
        applyShown(o, { x: f.x + (t.x - f.x) * e, z: f.z + (t.z - f.z) * e, y: f.y + (t.y - f.y) * e, rot: f.rot + angDiff(f.rot, t.rot) * e });
        if (glow) glow.scale.setScalar(1 + 0.9 * Math.sin(Math.PI * k));
        if (k >= 1) { o.anim = null; applyShown(o, o.cur); } else busy = true;
    });
    return busy;
}
function addTrail(a, b, color) {
    const T = B3.THREE;
    const ya = a.y, yb = b.y;
    const line = lineObj([new T.Vector3(a.x, ya, a.z), new T.Vector3(b.x, yb, b.z)], color, 0.7);
    line.material = line.material.clone(); line.userData.ownMat = true;
    addFx(line, lowQ() ? 900 : 1600, (k, f) => { f.obj.material.opacity = 0.7 * (1 - k); }, null, 'trail');
}

function removeToken(id) {
    const o = B3.objs[id];
    if (!o) return;
    B3.groups.tokens.remove(o.group);
    disposeTree(o.group);
    if (o.label && o.label.parentNode) o.label.parentNode.removeChild(o.label);
    delete B3.objs[id];
}
function clearAll() { B3.tape = null; clearGroup(B3.groups.tape); Object.keys(B3.objs).forEach(removeToken); clearGroup(B3.groups.overlay); clearGroup(B3.groups.preview); B3.overlayLabels = []; }
function clearGroup(g) { if (!g) return; while (g.children.length) { const c = g.children[0]; g.remove(c); disposeTree(c); } }

/* --- Overlay: arcs, range rings, ordnance, lock lines --- */
function addAnchorLabel(pos3, html, cls) { B3.overlayLabels.push({ pos: pos3, html, cls }); }
function sectorMesh(c, r, from, to, color, opacity) {
    const T = B3.THREE;
    const pts = [V(c.x, c.y, 1)];
    let span = ((to - from) % 360 + 360) % 360; if (span === 0) span = 360;
    const steps = Math.max(6, Math.ceil(span / 5));
    for (let i = 0; i <= steps; i++) {
        const a = (from + span * i / steps) * Math.PI / 180;
        pts.push(V(c.x + r * Math.sin(a), c.y - r * Math.cos(a), 1));
    }
    const pos = [], idx = [];
    pts.forEach(p => pos.push(p.x, p.y, p.z));
    for (let i = 1; i < pts.length - 1; i++) idx.push(0, i, i + 1);
    const g = new T.BufferGeometry();
    g.setAttribute('position', new T.Float32BufferAttribute(pos, 3));
    g.setIndex(idx);
    const m = new T.Mesh(g, mat('flat', color, opacity));
    m.userData.ownGeo = true;
    const grp = new T.Group();
    grp.add(m);
    grp.add(lineObj(span >= 360 ? pts.slice(1) : pts.concat([pts[0]]), color, 0.55));
    return grp;
}
function circleLine(c, r, color, opacity, dashed) {
    const pts = [];
    for (let i = 0; i <= 72; i++) { const a = i / 72 * Math.PI * 2; pts.push(V(c.x + r * Math.sin(a), c.y - r * Math.cos(a), 1.2)); }
    return lineObj(pts, color, opacity, dashed);
}
function rebuildOverlay(enc, visibleToks) {
    clearGroup(B3.groups.overlay);
    B3.overlayLabels = [];
    const T = B3.THREE;
    const ov = B3.groups.overlay;
    const byVessel = {};
    visibleToks.forEach(t => { byVessel[t.ship_marker_id] = t; });
    const selId = selectedVesselId();
    const selTok = selId && byVessel[selId];
    const selV = selTok && vesselById(selId);
    const tiers = window.BATTLE_RANGE_TIERS || { LONG: 400, MEDIUM: 200, SHORT: 100 };
    // Selected ship: arc wedges (firing arcs on) + faint range rings
    if (selTok && selV) {
        const c = tokCenter(selTok);
        if (!selV.is_strike_craft && window.firingArcsOn && window.firingArcsOn() && window.ARC_PRESETS) {
            const byArc = {};
            (selV.ship_weapons || []).filter(w => w && !w.is_point_defense).forEach(w => {
                const arc = window.weaponArc(w, selV);
                const r = Math.max(60, Math.min(w.range || 160, 420));
                byArc[arc] = Math.max(byArc[arc] || 0, r);
            });
            const facing = Number(selTok.facing) || 0;
            Object.keys(byArc).forEach(arc => {
                const p = window.ARC_PRESETS[arc];
                if (!p) return;
                (p.windows || [[0, 360]]).forEach(([from, to]) => {
                    ov.add(sectorMesh(c, byArc[arc], from + facing, p.windows ? to + facing : from + facing + 360, '#00e1ff', p.windows ? 0.13 : 0.05));
                });
            });
        }
        [['SHORT', tiers.SHORT, 0.5], ['MEDIUM', tiers.MEDIUM, 0.35], ['LONG', tiers.LONG, 0.25]].forEach(([n, r, op]) => {
            ov.add(circleLine(c, r, '#8fd8e4', op, true));
            addAnchorLabel(V(c.x, c.y - r, 2), `${n} ${r}`, 'b3d-ring-label');
        });
    }
    // Rings toggled with the 2D measuring tool (shared state, js/grid-tools.js)
    const gt = window.__gridTools;
    if (gt && gt.rings) gt.rings.forEach(id => {
        const t = byVessel[id];
        if (!t || id === selId) return;
        const c = tokCenter(t);
        [tiers.SHORT, tiers.MEDIUM, tiers.LONG].forEach((r, i) => ov.add(circleLine(c, r, '#8fd8e4', 0.45 - i * 0.1, true)));
    });
    // Missiles / torpedoes in flight (everyone)
    (enc.in_flight_ordnance || []).forEach(s => {
        const tt = byVessel[s.target_vessel_id];
        if (!tt) return;
        const src = byVessel[s.source_vessel_id];
        const a = src ? tokCenter(src) : (typeof s.launch_x === 'number' ? { x: s.launch_x, y: s.launch_y } : null);
        if (!a) return;
        const b = tokCenter(tt);
        const ta = window.battle3dAltitude(vesselById(s.target_vessel_id), tt);
        const sa = src ? window.battle3dAltitude(vesselById(s.source_vessel_id), src) : 20;
        const mid = V((a.x + b.x) / 2, (a.y + b.y) / 2, Math.max(sa, ta) + 40);
        const curve = new T.QuadraticBezierCurve3(V(a.x, a.y, sa), mid, V(b.x, b.y, ta));
        ov.add(lineObj(curve.getPoints(24), '#ff8a3d', 0.9, true));
        addAnchorLabel(mid, `⚠ ${esc(String(s.source_weapon_name || 'ORDNANCE').toUpperCase())} · IMPACT IN ${esc(s.turns_remaining)}`, 'b3d-ord-label');
    });
    // Target locks (tactical HUD) -- owner / DM only, same as the 2D lines
    const tv = window.__tv2;
    if (tv && tv.locks && typeof window.tv2Active === 'function' && window.tv2Active()) {
        Object.keys(tv.locks).forEach(vid => {
            const v = vesselById(vid), from = byVessel[vid];
            if (!from || !canControl(v)) return;
            const targets = new Set(Object.values(tv.locks[vid] || {}).filter(Boolean));
            targets.forEach(tid => {
                const to = byVessel[tid];
                if (!to) return;
                const a = tokCenter(from), b = tokCenter(to);
                ov.add(lineObj([V(a.x, a.y, window.battle3dAltitude(v, from)), V(b.x, b.y, window.battle3dAltitude(vesselById(tid), to))], '#00e1ff', 0.7, true));
            });
        });
    }
}

/* --- Sync (called on every Battle Map render while active) --- */
function syncScene() {
    const enc = window.globalBattleEncounterCache;
    if (!enc || !B3.renderer) return;
    if (enc.id !== B3.lastEncId) { clearAll(); B3.lastEncId = enc.id; B3.selectedLocal = null; resetCamera(); }
    resize();
    const currentTurnId = (enc.initiative_rolled && (enc.turn_order || []).length) ? enc.turn_order[enc.current_turn_index] : null;
    const selId = selectedVesselId();
    const seen = new Set();
    const visibleToks = [];
    (enc.tokens || []).forEach(tok => {
        const v = vesselById(tok.ship_marker_id);
        if (v && !visibleToMe(v)) return;
        seen.add(tok.token_id);
        visibleToks.push(tok);
        upsertToken(tok, v, enc, currentTurnId, selId);
    });
    Object.keys(B3.objs).forEach(id => { if (!seen.has(id)) removeToken(id); });
    rebuildOverlay(enc, visibleToks);
    drawTape();
    updateToolbar();
    const st = B3.el && B3.el.querySelector('.b3d-status');
    if (st) {
        st.style.display = window.battleMapArmedToken ? '' : 'none';
        if (window.battleMapArmedToken) st.textContent = 'Click the plane to place the ship · Esc / CANCEL in the palette to stop';
    }
    requestRender();
}
window.battle3dSync = syncScene;
function updateToolbar() {
    if (!B3.el) return;
    const selId = selectedVesselId();
    const tok = selId && encTokens().find(t => t.ship_marker_id === selId);
    const v = selId && vesselById(selId);
    const canTurn = !!(tok && typeof window.canTurnBattleToken === 'function' && window.canTurnBattleToken(tok).ok);
    const canAlt = !!(tok && v && canControl(v) && !v.is_station);
    const show = (act, on) => { const b = B3.el.querySelector(`[data-act="${act}"]`); if (b) b.style.display = on ? '' : 'none'; };
    show('turnL', canTurn); show('turnR', canTurn); show('altU', canAlt); show('altD', canAlt);
    const tapeBtn = B3.el.querySelector('[data-act="tape"]');
    if (tapeBtn) tapeBtn.classList.toggle('b3d-on', B3.tool === 'tape');
    const gt = window.__gridTools;
    show('share', B3.tool === 'tape');
    const shareBtn = B3.el.querySelector('[data-act="share"]');
    if (shareBtn) shareBtn.classList.toggle('b3d-on', !!(gt && gt.share));
    const qBtn = B3.el.querySelector('[data-act="quality"]');
    if (qBtn) qBtn.textContent = lowQ() ? '⚙ LOW' : '⚙ HIGH';
}
function onToolbar(e) {
    const btn = e.target.closest && e.target.closest('[data-act]');
    if (!btn) return;
    const act = btn.dataset.act;
    if (act === 'reset') return resetCamera();
    if (act === 'top') return topCamera();
    if (act === 'tape') { B3.tool = B3.tool === 'tape' ? null : 'tape'; if (!B3.tool) clearTape(); updateToolbar(); return; }
    if (act === 'share') { if (typeof window.toggleTapeShare === 'function') window.toggleTapeShare(); updateToolbar(); return; }
    if (act === 'quality') return window.setBattle3dQuality(lowQ() ? 'high' : 'low');
    const selId = selectedVesselId();
    const tok = selId && encTokens().find(t => t.ship_marker_id === selId);
    if (!tok) return;
    if (act === 'turnL') window.rotateBattleToken(tok.token_id, -15);
    if (act === 'turnR') window.rotateBattleToken(tok.token_id, 15);
    if (act === 'altU') window.nudgeBattleAltitude(tok.token_id, ALT_STEP);
    if (act === 'altD') window.nudgeBattleAltitude(tok.token_id, -ALT_STEP);
}

/* --- Rendering (on demand) --- */
const raf = (fn) => (window.requestAnimationFrame ? window.requestAnimationFrame(fn) : setTimeout(fn, 16));
function requestRender() {
    if (B3.pending || !B3.renderer) return;
    B3.pending = true;
    raf(() => { B3.pending = false; draw(); });
}
window.battle3dRequestRender = requestRender;
function projectToScreen(p) {
    const v = p.clone().project(B3.camera);
    return { x: (v.x + 1) / 2 * (B3._w || 0), y: (1 - v.y) / 2 * (B3._h || 0), behind: v.z > 1 };
}
function draw() {
    if (!B3.renderer || !B3.el || B3.el.style.display === 'none') return;
    applyCamera();
    const now = nowMs();
    const animating = stepAnims(now);
    stepFx(now);
    B3.renderer.render(B3.scene, B3.camera);
    B3.frames++;
    // Labels follow their 3D anchors
    Object.values(B3.objs).forEach(o => {
        const p = o.group.position.clone(); p.y = o.hull.position.y + (o.sig.startsWith('craft') ? 14 : 22);
        const s = projectToScreen(p);
        o.label.style.display = s.behind ? 'none' : '';
        o.label.style.transform = `translate(${s.x.toFixed(1)}px, ${s.y.toFixed(1)}px) translate(-50%, -100%)`;
    });
    const host = B3.el.querySelector('.b3d-labels');
    host.querySelectorAll('.b3d-anchor').forEach(n => n.remove());
    (B3.overlayLabels || []).concat(B3.previewLabels || [], B3.tapeLabels || []).forEach(a => {
        const s = projectToScreen(a.pos);
        if (s.behind) return;
        const n = document.createElement('div');
        n.className = `b3d-anchor ${a.cls || ''}`;
        n.innerHTML = a.html;
        n.style.transform = `translate(${s.x.toFixed(1)}px, ${s.y.toFixed(1)}px) translate(-50%, -50%)`;
        host.appendChild(n);
    });
    if (B3.fx.length || animating) requestRender();
}

/* --- Effects (Phase 6b) ---
   Every effect is a short-lived object in the fx group, stepped by draw()
   while any is alive (render on demand otherwise). LOW quality draws fewer
   particles and skips the outer glows. */
function nowMs() { return (window.performance && performance.now) ? performance.now() : Date.now(); }
function addFx(obj, life, update, onEnd, kind, delay) {
    if (!B3.renderer) return null;
    const f = { obj, life, update, onEnd, kind: kind || 'fx', t0: nowMs() + (delay || 0) };
    if (delay) obj.visible = false;
    B3.groups.fx.add(obj);
    B3.fx.push(f);
    requestRender();
    return f;
}
function stepFx(now) {
    const ended = [];
    B3.fx = B3.fx.filter(f => {
        if (now < f.t0) return true;
        f.obj.visible = true;
        const k = (now - f.t0) / f.life;
        if (k >= 1) { ended.push(f); return false; }
        try { if (f.update) f.update(k, f); } catch (e) {}
        return true;
    });
    ended.forEach(f => {
        B3.groups.fx.remove(f.obj);
        disposeFx(f.obj);
        if (f.onEnd) { try { f.onEnd(); } catch (e) {} }
    });
}
function disposeFx(obj) {
    obj.traverse(o => {
        if (o.geometry && (o.userData.ownGeo || o.userData.fxGeo)) o.geometry.dispose();
        if (o.material && (o.userData.ownMat || o.userData.fxMat)) o.material.dispose();
    });
}
function fxMat(color, opacity, additive) {
    const T = B3.THREE;
    return new T.MeshBasicMaterial({ color, transparent: true, opacity, depthWrite: false, blending: additive === false ? T.NormalBlending : T.AdditiveBlending, side: T.DoubleSide });
}
function fxMesh(geometry, material) { const m = new B3.THREE.Mesh(geometry, material); m.userData.fxGeo = true; m.userData.fxMat = true; return m; }
function altNear(gx, gy) {
    const t = tokenNear(gx, gy);
    return t ? window.battle3dAltitude(vesselById(t.ship_marker_id), t) : 30;
}
function tokenNear(gx, gy) {
    let best = null, bd = 30;
    encTokens().forEach(t => { const c = tokCenter(t); const d = Math.hypot(c.x - gx, c.y - gy); if (d < bd) { bd = d; best = t; } });
    return best;
}
function P3(g) { return V(g.x, g.y, altNear(g.x, g.y)); }
// A cylinder between two 3D points (beams, tracer bolts).
function rod(a, b, radius, material) {
    const T = B3.THREE;
    const len = a.distanceTo(b) || 0.01;
    const m = fxMesh(new T.CylinderGeometry(radius, radius, len, 6, 1, true), material);
    m.position.copy(a).add(b).multiplyScalar(0.5);
    m.quaternion.setFromUnitVectors(new T.Vector3(0, 1, 0), b.clone().sub(a).normalize());
    return m;
}
function flash(pos, r, color, life, grow, opacity, delay) {
    const T = B3.THREE;
    const m = fxMesh(new T.SphereGeometry(r, 14, 10), fxMat(color, opacity == null ? 0.9 : opacity));
    m.position.copy(pos);
    const op0 = m.material.opacity;
    addFx(m, life, (k) => { m.material.opacity = op0 * (1 - k); m.scale.setScalar(1 + k * (grow == null ? 1.5 : grow)); }, null, 'flash', delay);
    return m;
}
function sparks(pos, color, n, speed, life, delay) {
    const T = B3.THREE;
    const pts = new Float32Array(n * 3), vel = [];
    for (let i = 0; i < n; i++) {
        const th = Math.random() * Math.PI * 2, ph = Math.acos(2 * Math.random() - 1), sp = speed * (0.5 + Math.random() * 0.7);
        vel.push([Math.sin(ph) * Math.cos(th) * sp, Math.cos(ph) * sp * 0.6, Math.sin(ph) * Math.sin(th) * sp]);
        pts[i * 3] = pos.x; pts[i * 3 + 1] = pos.y; pts[i * 3 + 2] = pos.z;
    }
    const g = new T.BufferGeometry();
    g.setAttribute('position', new T.BufferAttribute(pts, 3));
    const m = new T.Points(g, new T.PointsMaterial({ color, size: 6, transparent: true, opacity: 1, depthWrite: false, blending: T.AdditiveBlending }));
    m.userData.fxGeo = true; m.userData.fxMat = true;
    addFx(m, life, (k) => {
        const arr = g.attributes.position.array, t = k * life / 1000;
        for (let i = 0; i < n; i++) { arr[i * 3] = pos.x + vel[i][0] * t; arr[i * 3 + 1] = pos.y + vel[i][1] * t; arr[i * 3 + 2] = pos.z + vel[i][2] * t; }
        g.attributes.position.needsUpdate = true;
        m.material.opacity = 1 - k;
    }, null, 'sparks', delay);
    return m;
}
function planeRing(pos, r0, r1, color, life, delay) {
    const T = B3.THREE;
    const m = fxMesh(new T.RingGeometry(0.85, 1, 48), fxMat(color, 0.8));
    m.rotation.x = -Math.PI / 2;
    m.position.set(pos.x, Math.max(1, pos.y), pos.z);
    addFx(m, life, (k) => { m.scale.setScalar(r0 + (r1 - r0) * k); m.material.opacity = 0.8 * (1 - k); }, null, 'ring', delay);
    return m;
}
// Where a shot lands: shields up -> blue bubble; shields down -> hull sparks.
function impactAt(gpt, delay) {
    const pos = P3(gpt);
    const tok = tokenNear(gpt.x, gpt.y);
    const v = tok && vesselById(tok.ship_marker_id);
    const shieldsUp = !!(v && (v.integrity_shields || 0) > 0);
    const low = lowQ();
    if (shieldsUp) {
        const T = B3.THREE;
        const r = (v.is_strike_craft ? 14 : v.is_station ? 34 : 30);
        const bub = fxMesh(new T.SphereGeometry(r, low ? 16 : 28, low ? 12 : 20), fxMat('#4db8ff', 0.42));
        bub.position.copy(pos);
        addFx(bub, 600, (k) => { bub.material.opacity = 0.42 * (1 - k); bub.scale.setScalar(0.88 + 0.22 * k); }, null, 'shield', delay);
        if (!low) flash(pos, 6, '#cfeeff', 280, 2, 0.9, delay);
        return 'shield';
    }
    flash(pos, 9, '#ffb066', 380, 2.2, 0.95, delay);
    sparks(pos, '#ff9a3d', low ? 7 : 18, 90, 700, delay);
    return 'hull';
}
window.battle3dImpactAt = impactAt; // for tests
function fireFx(family, s, t, color) {
    if (!window.battle3dActive() || !B3.renderer) return;
    const a = P3(s), b = P3(t);
    const low = lowQ();
    if (family === 'pulse') {                                   // healing
        planeRing(b, 10, 55, '#5dff9d', 1000);
        flash(b, 12, '#5dff9d', 800, 1.2, 0.5);
        if (!low) sparks(b, '#9dffbf', 10, 25, 900);
        return;
    }
    if (family === 'tracer') {                                  // kinetic: bolts that travel
        const n = low ? 2 : 4, flight = 300, gap = 80;
        const dir = b.clone().sub(a), len = dir.length() || 1;
        for (let i = 0; i < n; i++) {
            const bolt = rod(new B3.THREE.Vector3(0, 0, 0), dir.clone().normalize().multiplyScalar(Math.min(22, len * 0.3)), 1.7, fxMat(color, 1));
            const off = bolt.position.clone();
            addFx(bolt, flight, (k) => { bolt.position.copy(a).addScaledVector(dir, k).add(off); bolt.material.opacity = 1; }, i === n - 1 ? () => impactAt(t) : null, 'tracer', i * gap);
        }
        return;
    }
    if (family === 'burst') {                                   // explosive: a shell, then a cloud
        const shell = fxMesh(new B3.THREE.SphereGeometry(4.5, 10, 8), fxMat(color, 1));
        shell.position.copy(a);
        addFx(shell, 330, (k) => { shell.position.copy(a).lerp(b, k); }, () => {
            flash(b, 16, color, 700, 2.4, 0.7);
            sparks(b, color, low ? 10 : 26, 70, 850);
            impactAt(t);
        }, 'shell');
        return;
    }
    // beam (default): an instant glowing line that fades
    const core = rod(a, b, 1.6, fxMat('#ffffff', 0.95));
    addFx(core, 520, (k) => { core.material.opacity = 0.95 * (1 - k); }, null, 'beam');
    const glowRod = rod(a, b, low ? 3 : 5, fxMat(color, 0.5));
    addFx(glowRod, 650, (k) => { glowRod.material.opacity = 0.5 * (1 - k); }, null, 'beamglow');
    if (!low) flash(a, 6, color, 300, 1.5, 0.8);
    impactAt(t);
}
window.battle3dFireFx = fireFx; // for tests
function destructionFx(c) {
    if (!window.battle3dActive() || !B3.renderer) return;
    const pos = V(c.x, c.y, altNear(c.x, c.y));
    const low = lowQ();
    flash(pos, 16, '#ffffff', 350, 2, 1);
    flash(pos, 26, '#ff9a3d', 1100, 3, 0.85);
    if (!low) flash(pos, 20, '#ff4d1a', 1400, 4, 0.5, 120);
    planeRing(pos, 14, 170, '#ffb066', 1300);
    sparks(pos, '#ffb066', low ? 16 : 44, 130, 1500);
    if (!low) sparks(pos, '#ffffff', 14, 190, 800);
}
window.battle3dDestructionFx = destructionFx; // for tests
(function hookEffects() {
    const dom = window.DomBattleRenderer;
    if (dom && !dom.__b3dHooked) {
        const origFire = dom.fireEffect;
        dom.fireEffect = function (sx, sy, tx, ty, color, family) {
            const r = origFire.apply(this, arguments);
            try { fireFx(family || 'beam', { x: sx, y: sy }, { x: tx, y: ty }, color || '#ff3333'); } catch (e) { console.error('3D view: effect failed', e); }
            return r;
        };
        dom.__b3dHooked = true;
    }
    if (typeof window.spawnDestructionEffect === 'function' && !window.spawnDestructionEffect.__b3d) {
        const origBoom = window.spawnDestructionEffect;
        const wrapped = function (grid, x, y) {
            const r = origBoom.apply(this, arguments);
            try { destructionFx({ x: x + BATTLE_TOKEN_SIZE / 2, y: y + BATTLE_TOKEN_SIZE / 2 }); } catch (e) {}
            return r;
        };
        wrapped.__b3d = true;
        window.spawnDestructionEffect = wrapped;
    }
})();

/* --- Measuring tape (Phase 6b) --- same range bands as the 2D tape; shares
   through the same broadcast, and shows tapes shared from the 2D view. */
function tapeObjects(a, b, color, labelHtml, cls) {
    const T = B3.THREE;
    const g = new T.Group();
    const pa = V(a.x, a.y, 2), pb = V(b.x, b.y, 2);
    g.add(lineObj([pa, pb], color, 0.95));
    g.add(circleLine(a, 4, color, 0.9));
    g.add(circleLine(b, 4, color, 0.9));
    return { g, label: { pos: pa.clone().add(pb).multiplyScalar(0.5).setY(6), html: labelHtml, cls } };
}
function drawTape() {
    clearGroup(B3.groups.tape);
    B3.tapeLabels = [];
    if (B3.tape) {
        const t = tapeObjects(B3.tape.a, B3.tape.b, '#ffe066', esc(window.tapeLabel ? window.tapeLabel(B3.tape.a, B3.tape.b) : ''), 'b3d-tape-label');
        B3.groups.tape.add(t.g); B3.tapeLabels.push(t.label);
    }
    const gt = window.__gridTools;
    const now = Date.now();
    ((gt && gt.remoteTapes) || []).filter(r => r.until > now).forEach(r => {
        const t = tapeObjects(r.a, r.b, '#c9a6ff', `${esc(r.who || '')} · ${esc(window.tapeLabel ? window.tapeLabel(r.a, r.b) : '')}`, 'b3d-tape-label b3d-tape-remote');
        B3.groups.tape.add(t.g); B3.tapeLabels.push(t.label);
    });
    requestRender();
}
function clearTape() { B3.tape = null; drawTape(); }
function shareTape3d() {
    const gt = window.__gridTools;
    if (!gt || !gt.share || !B3.tape || typeof window.sendBattleBroadcast !== 'function') return;
    const profs = (typeof allProfiles !== 'undefined' && Array.isArray(allProfiles)) ? allProfiles : [];
    const me = profs.find(p => p.id === currentUserId);
    const who = currentUserRole === 'dm' ? 'DM' : ((me && me.username) || 'player');
    window.sendBattleBroadcast('fx', { k: 'tape', a: B3.tape.a, b: B3.tape.b, who });
}
(function hookRemoteTape() {
    const orig = window.showRemoteTape;
    if (typeof orig !== 'function' || orig.__b3d) return;
    const wrapped = function () {
        const r = orig.apply(this, arguments);
        try { if (window.battle3dActive() && B3.renderer) { drawTape(); setTimeout(drawTape, 6100); } } catch (e) {}
        return r;
    };
    wrapped.__b3d = true;
    window.showRemoteTape = wrapped;
})();

/* --- Picking --- */
function rayAt(clientX, clientY) {
    const T = B3.THREE;
    const rect = B3.renderer.domElement.getBoundingClientRect ? B3.renderer.domElement.getBoundingClientRect() : { left: 0, top: 0, width: B3._w, height: B3._h };
    const w = rect.width || B3._w || 1, h = rect.height || B3._h || 1;
    const ndc = new T.Vector2(((clientX - rect.left) / w) * 2 - 1, -((clientY - rect.top) / h) * 2 + 1);
    applyCamera();
    B3.scene.updateMatrixWorld(); // positions may have changed since the last frame
    const rc = new T.Raycaster();
    rc.setFromCamera(ndc, B3.camera);
    return rc;
}
function planeHit(clientX, clientY) {
    const T = B3.THREE;
    const rc = rayAt(clientX, clientY);
    const out = new T.Vector3();
    const hit = rc.ray.intersectPlane(new T.Plane(new T.Vector3(0, 1, 0), 0), out);
    return hit ? toGrid(out) : null;
}
window.battle3dScreenToWorld = function (clientX, clientY) { return B3.renderer ? planeHit(clientX, clientY) : null; };
window.battle3dPickToken = function (clientX, clientY) {
    if (!B3.renderer) return null;
    const rc = rayAt(clientX, clientY);
    const targets = [];
    Object.values(B3.objs).forEach(o => { targets.push(o.hull, o.disc); });
    const hits = rc.intersectObjects(targets, true);
    const h = hits.find(x => x.object.userData && x.object.userData.tokenId);
    return h ? { tokenId: h.object.userData.tokenId, vesselId: h.object.userData.vesselId } : null;
};
// Where the projected screen point of a token's centre is (used by tests / tooltips).
window.battle3dTokenScreenPos = function (tokenId) {
    const o = B3.objs[tokenId];
    if (!o || !B3.renderer) return null;
    applyCamera();
    const rect = B3.renderer.domElement.getBoundingClientRect ? B3.renderer.domElement.getBoundingClientRect() : { left: 0, top: 0 };
    const p = o.group.position.clone(); p.y = o.hull.position.y;
    const s = projectToScreen(p);
    return { x: rect.left + s.x, y: rect.top + s.y };
};

/* --- Input: orbit / pan / zoom / select / move / place --- */
function wireInput(el) {
    const host = el.querySelector('.b3d-canvas-host');
    host.addEventListener('contextmenu', e => e.preventDefault());
    host.addEventListener('wheel', e => {
        if (!B3.renderer) return;
        e.preventDefault();
        B3.cam.dist = Math.max(220, Math.min(2600, B3.cam.dist * Math.exp((e.deltaY || 0) * 0.0012)));
        requestRender();
    }, { passive: false });
    host.addEventListener('pointerdown', e => onDown(e));
    window.addEventListener('pointermove', e => onMove(e));
    window.addEventListener('pointerup', e => onUp(e));
    window.addEventListener('pointercancel', e => { delete B3.pointers[e.pointerId]; cancelDrag(); });
}
window.battle3dPointer = { down: (e) => onDown(e), move: (e) => onMove(e), up: (e) => onUp(e) }; // for tests
function ptrList() { return Object.values(B3.pointers); }
function onDown(e) {
    if (!B3.renderer || !window.battle3dActive()) return;
    B3.pointers[e.pointerId] = { x: e.clientX, y: e.clientY };
    if (e.target && e.target.setPointerCapture && e.pointerId !== undefined) { try { e.target.setPointerCapture(e.pointerId); } catch (err) {} }
    const ps = ptrList();
    if (ps.length === 2) {
        cancelDrag();
        const [a, b] = ps;
        B3.drag = { kind: 'pinch', d0: Math.hypot(a.x - b.x, a.y - b.y) || 1, dist0: B3.cam.dist, mx: (a.x + b.x) / 2, my: (a.y + b.y) / 2, tx0: B3.cam.tx, tz0: B3.cam.tz };
        return;
    }
    if (ps.length > 2) return;
    const base = { sx: e.clientX, sy: e.clientY, moved: false, button: e.button || 0 };
    if (B3.tool === 'tape' && base.button === 0 && !e.shiftKey) {
        const pk = window.battle3dPickToken(e.clientX, e.clientY);
        const tk = pk && encTokens().find(t => t.token_id === pk.tokenId);
        const a = tk ? tokCenter(tk) : planeHit(e.clientX, e.clientY);
        B3.drag = Object.assign(base, { kind: 'tape', a });
        return;
    }
    const pick = (base.button === 0 && !e.shiftKey) ? window.battle3dPickToken(e.clientX, e.clientY) : null;
    if (pick) {
        const tok = encTokens().find(t => t.token_id === pick.tokenId);
        const rule = window.battleMoveRule(pick.tokenId, pick.vesselId);
        const v = vesselById(pick.vesselId);
        const size = tokSize(v);
        const c = tok ? tokCenter(tok) : { x: 0, y: 0 };
        const hit = planeHit(e.clientX, e.clientY) || c;
        B3.drag = Object.assign(base, { kind: 'ship', tokenId: pick.tokenId, vesselId: pick.vesselId, rule, size, grab: { x: c.x - hit.x, y: c.y - hit.y } });
    } else if (base.button === 2 || base.button === 1 || e.shiftKey) {
        B3.drag = Object.assign(base, { kind: 'pan', tx0: B3.cam.tx, tz0: B3.cam.tz });
    } else {
        B3.drag = Object.assign(base, { kind: window.battleMapArmedToken ? 'place' : 'orbit', yaw0: B3.cam.yaw, pitch0: B3.cam.pitch });
    }
}
function panBy(dx, dy, tx0, tz0) {
    const c = B3.cam, y = c.yaw * Math.PI / 180, p = Math.max(0.25, Math.sin(c.pitch * Math.PI / 180));
    const s = c.dist * 2 * Math.tan(22.5 * Math.PI / 180) / (B3._h || 600);
    const rx = Math.cos(y), rz = -Math.sin(y);      // screen right on the plane
    const fx = -Math.sin(y), fz = -Math.cos(y);     // screen up on the plane
    c.tx = Math.max(-BATTLE_GRID_W, Math.min(BATTLE_GRID_W, tx0 - rx * dx * s + fx * dy * s / p));
    c.tz = Math.max(-BATTLE_GRID_H, Math.min(BATTLE_GRID_H, tz0 - rz * dx * s + fz * dy * s / p));
}
function onMove(e) {
    if (!B3.drag) return;
    if (B3.pointers[e.pointerId]) B3.pointers[e.pointerId] = { x: e.clientX, y: e.clientY };
    const d = B3.drag;
    if (d.kind === 'pinch') {
        const ps = ptrList(); if (ps.length < 2) return;
        const [a, b] = ps;
        const dd = Math.hypot(a.x - b.x, a.y - b.y) || 1;
        B3.cam.dist = Math.max(220, Math.min(2600, d.dist0 * d.d0 / dd));
        panBy((a.x + b.x) / 2 - d.mx, (a.y + b.y) / 2 - d.my, d.tx0, d.tz0);
        requestRender();
        return;
    }
    const dx = e.clientX - d.sx, dy = e.clientY - d.sy;
    if (Math.abs(dx) > 5 || Math.abs(dy) > 5) d.moved = true;
    if (!d.moved) return;
    if (d.kind === 'orbit') {
        B3.cam.yaw = d.yaw0 - dx * 0.35;
        B3.cam.pitch = Math.max(12, Math.min(89.5, d.pitch0 + dy * 0.3));
        requestRender();
    } else if (d.kind === 'pan') {
        panBy(dx, dy, d.tx0, d.tz0);
        requestRender();
    } else if (d.kind === 'tape' && d.a) {
        const hit = planeHit(e.clientX, e.clientY);
        if (!hit) return;
        B3.tape = { a: d.a, b: hit };
        drawTape();
    } else if (d.kind === 'ship' && d.rule.mode !== 'tap') {
        const hit = planeHit(e.clientX, e.clientY);
        if (!hit) return;
        const cx = hit.x + d.grab.x, cy = hit.y + d.grab.y;
        d.pos = window.battleConstrainMove(d.rule, cx - d.size / 2, cy - d.size / 2);
        showMovePreview(d);
    }
}
function showMovePreview(d) {
    const o = B3.objs[d.tokenId];
    clearGroup(B3.groups.preview);
    B3.previewLabels = [];
    if (!o || !d.pos) return;
    const c = { x: d.pos.x + d.size / 2, y: d.pos.y + d.size / 2 };
    const s = { x: d.rule.x0 + d.size / 2, y: d.rule.y0 + d.size / 2 };
    o.group.position.copy(V(c.x, c.y, 0));
    B3.groups.preview.add(lineObj([V(s.x, s.y, 1.5), V(c.x, c.y, 1.5)], '#ffffff', 0.8, true));
    const dist = Math.hypot(d.pos.x - d.rule.x0, d.pos.y - d.rule.y0);
    const cap = d.rule.mode === 'capped' ? ` / ${Math.round(d.rule.maxReach)}` : '';
    B3.previewLabels.push({ pos: V((s.x + c.x) / 2, (s.y + c.y) / 2, 4), html: `${Math.round(dist)}${cap} px`, cls: 'b3d-move-label' });
    requestRender();
}
function cancelDrag() {
    const d = B3.drag;
    B3.drag = null;
    clearGroup(B3.groups.preview);
    B3.previewLabels = [];
    if (d && d.kind === 'ship') syncScene();
}
function onUp(e) {
    delete B3.pointers[e.pointerId];
    const d = B3.drag;
    if (!d) return;
    if (d.kind === 'pinch') { if (ptrList().length < 2) B3.drag = null; return; }
    B3.drag = null;
    clearGroup(B3.groups.preview);
    B3.previewLabels = [];
    if (d.kind === 'ship') {
        if (!d.moved) {
            B3.selectedLocal = d.vesselId;
            window.battleTokenTapped(d.vesselId);
            syncScene();
            return;
        }
        if (d.rule.mode === 'tap') {
            if (d.rule.blockReason) alert(d.rule.blockReason);
            syncScene();
            return;
        }
        if (d.pos) { window.battle3dCommitDragPosition(d.tokenId, d.pos.x + d.size / 2, d.pos.y + d.size / 2); window.battleCommitMove(d.rule, d.pos); }
        else syncScene();
        return;
    }
    if (d.kind === 'tape') {
        if (!d.moved) clearTape(); else shareTape3d();
        return;
    }
    if (d.kind === 'place' && !d.moved) {
        const hit = planeHit(e.clientX, e.clientY);
        if (hit && hit.x >= 0 && hit.y >= 0 && hit.x <= BATTLE_GRID_W && hit.y <= BATTLE_GRID_H) window.placeArmedTokenAt(hit);
        return;
    }
    if (d.kind === 'orbit' && !d.moved && B3.selectedLocal) { B3.selectedLocal = null; syncScene(); }
    requestRender();
}

/* --- Show / hide with the Battle Map --- */
function syncView() {
    ensureHeaderButton();
    const wrap = document.getElementById('battle-map-grid-wrap');
    if (!window.battle3dActive()) {
        if (B3.el) B3.el.style.display = 'none';
        if (wrap) wrap.style.display = '';
        if (B3.drag) B3.drag = null;
        return;
    }
    if (!ensureEls()) return;
    B3.el.style.display = '';
    if (wrap) wrap.style.display = 'none';
    if (!B3.hintShown) { B3.hintShown = true; setTimeout(() => { const h = B3.el && B3.el.querySelector('.b3d-hint'); if (h) h.classList.add('b3d-hint-fade'); }, 9000); }
    if (!B3.THREE) {
        const st = B3.el.querySelector('.b3d-status');
        if (st) { st.style.display = ''; st.textContent = 'Loading 3D view…'; }
        loadThree().then(() => {
            if (!B3.renderer) initScene();
            syncScene();
        }).catch(() => {
            if (typeof window.renderBattleMapPanel === 'function') window.renderBattleMapPanel(); // falls back to the 2D grid
        });
        return;
    }
    if (!B3.renderer) {
        try { initScene(); }
        catch (err) {
            console.error('3D view: WebGL start-up failed -- falling back to the 2D grid', err);
            B3.failed = true;
            syncView();
            return;
        }
    }
    syncScene();
}
window.battle3dSyncView = syncView;
// Phone + 3D: the tactical HUD's bottom sheet starts as a slim bar (name,
// tags, buttons). Tapping the name toggles it; WEAPONS ▸ still opens fully.
function narrowScreen() { try { return window.matchMedia('(max-width: 768px)').matches; } catch (e) { return false; } }
function applyMiniSheet() {
    const box = document.getElementById('tv2-hud');
    if (!box) return;
    const on = narrowScreen() && window.battle3dActive();
    box.classList.toggle('b3d-mini', on && B3.sheetMini);
    box.classList.toggle('b3d-mini-able', on);
    if (!box.__b3dMini) {
        box.__b3dMini = true;
        box.addEventListener('click', e => {
            if (!box.classList.contains('b3d-mini-able') || box.classList.contains('tv2-open')) return;
            if (!(e.target.closest && e.target.closest('.tv2-hero'))) return;
            B3.sheetMini = !B3.sheetMini;
            applyMiniSheet();
        });
    }
}
window.battle3dApplyMiniSheet = applyMiniSheet;
(function hookRender() {
    const orig = window.renderBattleMapPanel;
    if (typeof orig !== 'function' || orig.__b3dHooked) return;
    const hooked = function (...args) {
        const r = orig.apply(this, args);
        try { syncView(); applyMiniSheet(); } catch (err) { console.error('3D view: render failed', err); }
        return r;
    };
    hooked.__b3dHooked = true;
    hooked.__tv2Hooked = orig.__tv2Hooked;
    window.renderBattleMapPanel = hooked;
})();
(function hookSelect() {
    const orig = window.tv2Select;
    if (typeof orig !== 'function' || orig.__b3d) return;
    const wrapped = function () {
        const r = orig.apply(this, arguments);
        try { if (window.battle3dActive() && B3.renderer) syncScene(); } catch (e) {}
        return r;
    };
    wrapped.__b3d = true;
    window.tv2Select = wrapped;
})();
try {
    document.addEventListener('darkforest:features-changed', () => { if (window.globalBattleEncounterCache) { try { syncView(); } catch (e) {} } });
    document.addEventListener('keydown', e => {
        if (e.key !== 'Escape' || !window.battle3dActive()) return;
        if (B3.drag) cancelDrag();
        else if (B3.tape) clearTape();
    });
} catch (e) {}
})();
